# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logs_pb2 as logs__pb2


class LogRetrieverStub(object):
    """Log Retrieving Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessages = channel.unary_unary(
                '/logs.LogRetriever/GetMessages',
                request_serializer=logs__pb2.GetMessageReq.SerializeToString,
                response_deserializer=logs__pb2.MessagesReply.FromString,
                )


class LogRetrieverServicer(object):
    """Log Retrieving Service Definition
    """

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogRetrieverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=logs__pb2.GetMessageReq.FromString,
                    response_serializer=logs__pb2.MessagesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logs.LogRetriever', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogRetriever(object):
    """Log Retrieving Service Definition
    """

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logs.LogRetriever/GetMessages',
            logs__pb2.GetMessageReq.SerializeToString,
            logs__pb2.MessagesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
